### ISSUE TITLE
Evaluation on other datasets

### ISSUE THREAD

**Issue by nuistji** [lovelyqian/Meta-FDMixup#1]
Excellent work and thank you for your release!  I have one question to ask you: since the setting of your task is cross-domain few-shot learning, have you evaluated your method on the other four datasets (CropDisease, EuroSAT, ISIC and ChestX, the benchmark is set by [1]), whose domain shifts are larger than the other datasets (Places, Cars, Plantae and CUB)? 

[1] Guo Y, Codella N C, Karlinsky L, et al. A broader study of cross-domain few-shot learning. ECCV 2020.

**Comment by lovelyqian** [comment]
Thanks for your question！Factually, we have not conducted the experiments on the BSCDFSL benchmark in the conference version. However, to better show the effectiveness of our method, we are trying to do these experiments as extension work.
