### ISSUE TITLE
The issue of forming the auxiliary dataset

### ISSUE THREAD

**Issue by tinkez** [lovelyqian/Meta-FDMixup#10]
Thank you for this open-source work. However I still have some questions about the selection of the auxiliary set, could you please point out the code you used on randomly selecting $num_{target}$ labeled images from the target base set?

**Comment by lovelyqian** [comment]
It is just randomly sampled $num_{target}$ labeled examples from the target base set.

**Comment by lovelyqian** [comment]
> Thank you for this open-source work. However I still have some questions about the selection of the auxiliary set, could you please point out the code you used on randomly selecting numtarget labeled images from the target base set?

Hi,  I just uploaded the code: https://github.com/lovelyqian/Meta-FDMixup/blob/main/process_labeled_target_data.py, Hope it helps.

**Comment by lovelyqian** [comment]
> Thank you for this open-source work. However I still have some questions about the selection of the auxiliary set, could you please point out the code you used on randomly selecting numtarget labeled images from the target base set?

Hi, @ypaTinke , I just uploaded the code: https://github.com/lovelyqian/Meta-FDMixup/blob/main/process_labeled_target_data.py

**Comment by tinkez** [comment]
Thank you for your reply, it's very helpful.
