### ISSUE TITLE
Test about the choice of features

### ISSUE THREAD

**Issue by Henkwu** [lovelyqian/Meta-FDMixup#3]
This is excellent work, and thanks for providing the code. I have a question in this paper, that is,  in the test stage,  why do you choose domain-irrelevant features to attain accuracy instead of domain-specific features?  I hope that through your explanation, my confusion can be resolved. Thank you！

**Comment by lovelyqian** [comment]
Thanks for your question!   We learn to disentangle the domain-irrelevant and domain-specific features. Typically, the domain-specific features mainly contain the domain information. In other words, given an image, the domain-specific features can be used to classify which domain it belongs to.  Thus, it is not suitable to classify the semantic category by the domain-specific features. On the other hand, our domain-irrelevant features are supposed to extract the main semantic information.
