### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by EricLee0224** [lovelyqian/Meta-FDMixup#4]
学姐好，感谢代码开源，mix和解耦模块真的很有意思！打算复现感受一下，请问数据集的下载的解释能否再稍微详细一点Orz
下载好的数据集应该放到哪呢？
数据集的文件结构大概是什么样的？
谢谢！

**Comment by lovelyqian** [comment]
感谢关注！

数据集的处理这个link给的比较详细：https://github.com/wyharveychen/CloserLookFewShot#self-defined-setting

**Comment by lovelyqian** [comment]
也可以参考这个：https://github.com/Haoqing-Wang/CDFSL-ATA

**Comment by lovelyqian** [comment]
然后只需要保证训练和测试脚本所需要的路径都是正确的就好了 （sources/labeled data json 中需要替换一下路径地址）

**Comment by EricLee0224** [comment]
芜湖！感谢学姐，已解决！
