### ISSUE TITLE
Partitioning of classes in the auxiliary dataset

### ISSUE THREAD

**Issue by MAGIC-XINE** [lovelyqian/Meta-FDMixup#5]
Hello, thank you for the code. When reappearing, I found that the label_base_xxx_X. json file provided by sources in your Github seems to have one class less (for example, the base class of CUB divided in FWT is 100 classes. But the label_base_cub_5.json you provided seems to have only 99 classes (0-98)).
_Data partitioning in FWT_
![image](https://user-images.githubusercontent.com/91297843/188455409-eb85b70a-28a1-4294-9dc6-e001ee396355.png)
 _label_base_cub_5. json in sources_
![W4}2H70(V0OBOS(W68` S55](https://user-images.githubusercontent.com/91297843/188455585-3c5073de-8197-4619-a4c7-d2e26a1f964c.png)

**Comment by MAGIC-XINE** [comment]
@lovelyqian

**Comment by lovelyqian** [comment]
Thanks for your kind reminder.  After checking the json file, I find that you are correct.  So, I feel sorry for this mistake and will update the right json files in our extension work. :( By the way, this issue does not affect the main setting of our work, and if you expand the auxiliary target training classes (e.g. from 99 to 100), the performance would be better.

**Comment by MAGIC-XINE** [comment]
Thank you for your reply！
