### ISSUE TITLE
How to eval baseline?

### ISSUE THREAD

**Issue by SmartNight-cc** [lovelyqian/Meta-FDMixup#7]
Hello, I am a beginner in this field ！May I know how you tested the performance of baseline by modifying the code? It is the s-base mentioned in the article.(☆▽☆)

**Comment by lovelyqian** [comment]
you can test the performance of baseline model by: 
python network_test.py --ckp_path output/checkpoints/your-baseline-model/xx.tar --stage metatrain --dataset miniImagenet --n_shot 5
