### ISSUE TITLE
测试准确率达不到

### ISSUE THREAD

**Issue by perfectlxy7** [lovelyqian/Meta-FDMixup#8]
作者您好，我用你给的预训练模型进行了测试，在CUB，Cars ，Places数据集中的测试结果达到了论文中表二2的效果，但是在Plantae数据集上的准确率基本只能达到67%点多，与表中69.22%有一定差距，请问会是什么原因呢，求解答，谢谢！

**Comment by lovelyqian** [comment]
We check the results before releasing the codes.  

wish the following steps could help: 
1.  we provide our trained checkpoints, how about the testing result of them?  
2.  model may be sensitive to different seeds, though we have fixed all the seeds, results may still vary on different machines. Maybe you can try some other seeds?
